dist: trusty
sudo: false
language: go
go:
- 1.9
env:
- CONSUL_VERSION=1.0.0
before_install:
- curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
- unzip consul.zip
- mkdir -p ~/bin
- mv consul ~/bin
- export PATH="~/bin:$PATH"
script:
- find . -type f -name "*go" | xargs sed 's|github.com/hashicorp/consul-template|github.com/criteo-forks/consul-template|'
  -i
- make test
- export XC_OS=linux; export XC_ARCH=amd64 ; make dev
- find . -type f
deploy:
  provider: releases
  api_key:
    secure: b16v531JvuHT71t98gNJ9y6Fqhw2MoAIh/Ug2GfAqd3h8CyXO1mJaY44S/v21MYiL2vownDGcwEx0soKWnNG8ZMNEgArZWYxsCAAHe2Wm3Sz0xz7lkFf1XTKAoGSwzBdOMk8oTZG2ry89S93CPkYOBZu9KCwAXUBF2fvZ7h4u39YZaYhyxnf/p8QwSc9ugj/XaYyQvU1wBfZpE3we4S7Y1DLTVv3z92i9BOPyMVF3gJg7XxbCqba/+5ERzgLNbQ+O/IfyiN31SWP7JfrEUgba9EfKedlEH8K88aEiGBYDU5dFYNAF2dcZgRrEECJN++/C0XPn/uK3BiE9Mimsyg8Bfe1JUOZT7sM+wPpsf81iKmrd50Oveb6ICd6A5wZ5qcKN1mL8JsYLDAyjJ/OrP8rs3+lucLzdF/X+e9mIO/dADZabhkoTvqP5MvBW8NEfnoek8CYib3MtHYKsUE6PoBZVv3zu2XbNxtgwIE35Khuymz/mEQJbfiIQUzy5ORWie2Tamky0FEWpJ1lCkWbjbtacsSBwag1+i0cqcZ/i6YKA9ghZfN8T8e1oL6UssRbD9r+4gW56+BwDrJV8YdV47GddVC6svdUFYHmAxCalavHTuOcRkA2th+OG6caB0mSrBYgK7IrSiL96xT7zvtuAesLRQNtMOzZ0GYEves8fX8irwU=
  file: pkg/linux_amd64/consul-template
  on:
    tags: true
